//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorDataFormLocalization.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SfResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SfResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorDataFormLocalization.Client.Resources.SfResources", typeof(SfResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DaaForm_DateOfBirth {
            get {
                return ResourceManager.GetString("DaaForm_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept the terms and conditions.
        /// </summary>
        public static string DataForm_AcceptTerms {
            get {
                return ResourceManager.GetString("DataForm_AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Accept the terms and conditions..
        /// </summary>
        public static string DataForm_AcceptTerms_Error {
            get {
                return ResourceManager.GetString("DataForm_AcceptTerms_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date..
        /// </summary>
        public static string DataForm_DateOfBirth_Error {
            get {
                return ResourceManager.GetString("DataForm_DateOfBirth_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string DataForm_Email {
            get {
                return ResourceManager.GetString("DataForm_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address..
        /// </summary>
        public static string DataForm_Email_Error {
            get {
                return ResourceManager.GetString("DataForm_Email_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string DataForm_FirstName {
            get {
                return ResourceManager.GetString("DataForm_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your first name..
        /// </summary>
        public static string DataForm_FirstName_Error {
            get {
                return ResourceManager.GetString("DataForm_FirstName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string DataForm_LastName {
            get {
                return ResourceManager.GetString("DataForm_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your last name..
        /// </summary>
        public static string DataForm_LastName_Error {
            get {
                return ResourceManager.GetString("DataForm_LastName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string DataForm_Password {
            get {
                return ResourceManager.GetString("DataForm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password..
        /// </summary>
        public static string DataForm_Password_Error {
            get {
                return ResourceManager.GetString("DataForm_Password_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be minimum 8 characters..
        /// </summary>
        public static string DataForm_Password_Length_Error {
            get {
                return ResourceManager.GetString("DataForm_Password_Length_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string DataForm_Submit {
            get {
                return ResourceManager.GetString("DataForm_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string DataForm_Valid_Email_Error {
            get {
                return ResourceManager.GetString("DataForm_Valid_Email_Error", resourceCulture);
            }
        }
    }
}
